title: Paula Naomi
logo: "https://media.licdn.com/dms/image/v2/C5603AQFY67oETGdqgw/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1517353218124?e=1741824000&v=beta&t=InNLCu7sg5pglNpHuwJafKA9x24gSjeusl28n71Mzlw"
description: >
  <br><br>
  <br><br>
  I'm Paula, a Chemical Engineer that has spent the last 15 or so years working with data from industrial chemical plants. I have a master's and doctorate degree in Chemical Engineering specifically in modelling, simulation and control of industrial chemical processes. 
  <br><br>
  I currently work at a biotech startup creating digital solutions for monitoring and controlling industrial fermentation processes. My main areas of interest are mathematical modelling, simulation and data science. 
  <br><br>
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
